kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-pods
  namespace: default
subjects:
- kind: User
  name: deploy
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployer
  apiGroup: rbac.authorization.k8s.io
